### ISSUE TITLE
Consolidation of team resource repositories

### ISSUE THREAD

**Issue by kevinjuan25** [AguaClara/team_lead#1]
I think it might be useful to consolidate team resources into one repository so that we can limit the number of repositories having only a singular purpose (i.e. syllabus and team roster are being used for Wiki capabilities). You can rename one of the repositories to team_resources, and set the purpose to something like "A repository containing x, y, z information about the team" and delete the other. Then you can direct members to that one repo with all of that information rather than having all that info spread out into multiple repositories. It's a better organization method especially as everyone is still getting used to GitHub.

**Comment by sidneylok** [comment]
This is a great idea! We'll get on that.
